'use client'

import { useState } from 'react'
import { useRouter } from 'next/navigation'
import Link from 'next/link'
import { useForm } from 'react-hook-form'
import { zodResolver } from '@hookform/resolvers/zod'
import { toast } from 'sonner'
import { ArrowLeft } from 'lucide-react'
import { Form } from '@/components/ui/form'
import { Button } from '@/components/ui/button'
import { ProductFormFields } from '@/components/seller/ProductFormFields'
import { PhotoUploader, type PhotoFile } from '@/components/seller/PhotoUploader'
import { productSchema, type ProductInput } from '@/lib/validations/product'
import { uploadImage } from '@/lib/utils/image'
import { createClient } from '@/lib/supabase/client'

export default function NuevoProductoPage() {
  const router = useRouter()
  const [photos, setPhotos] = useState<PhotoFile[]>([])
  const [photoError, setPhotoError] = useState<string | null>(null)
  const [submitting, setSubmitting] = useState(false)

  const form = useForm<ProductInput>({
    resolver: zodResolver(productSchema),
    defaultValues: {
      price: undefined,
      size: undefined,
      category: undefined,
      condition: undefined,
      gender: undefined,
      title: '',
      description: '',
      brand: '',
      color: '',
      material: '',
    },
  })

  async function onSubmit(values: ProductInput) {
    if (photos.length === 0) {
      setPhotoError('Agrega al menos una foto')
      return
    }
    setPhotoError(null)
    setSubmitting(true)

    const supabase = createClient()
    let productId: string | null = null

    try {
      const { data: { user }, error: authError } = await supabase.auth.getUser()
      if (authError || !user) throw new Error('No autenticado')

      // Get seller's store
      const { data: store, error: storeError } = await supabase
        .from('stores')
        .select('id')
        .eq('owner_id', user.id)
        .maybeSingle()
      if (storeError || !store) throw new Error('No se encontró tu tienda')

      // Insert product
      const { data: product, error: productError } = await supabase
        .from('products')
        .insert({
          store_id: store.id,
          title: values.title?.trim() || null, // null → auto-generated by DB trigger
          price: values.price,
          size: values.size,
          category: values.category,
          condition: values.condition,
          gender: values.gender,
          description: values.description?.trim() || null,
          brand: values.brand?.trim() || null,
          color: values.color?.trim() || null,
          material: values.material?.trim() || null,
          status: 'active',
        })
        .select('id')
        .single()

      if (productError || !product) {
        console.error('Product insert error:', productError?.message)
        throw new Error('Error al crear el producto')
      }

      productId = product.id

      // Upload each photo
      const imageInserts: Array<{ product_id: string; url: string; storage_path: string; position: number }> = []

      for (let i = 0; i < photos.length; i++) {
        const storagePath = `${user.id}/${product.id}/${i}.jpg`
        const { publicUrl, storagePath: savedPath } = await uploadImage(
          photos[i].file,
          'product-images',
          storagePath
        )
        imageInserts.push({
          product_id: product.id,
          url: publicUrl,
          storage_path: savedPath,
          position: i,
        })
      }

      const { error: imagesError } = await supabase
        .from('product_images')
        .insert(imageInserts)

      if (imagesError) {
        console.error('product_images insert error:', imagesError.message)
        throw new Error('Error al guardar las fotos')
      }

      toast.success('¡Producto publicado!')
      router.push('/seller/productos')
      router.refresh()
    } catch (err) {
      const message = err instanceof Error ? err.message : 'Error inesperado'
      toast.error(message)
      console.error('Product create error:', err)

      // Rollback: delete the product row if it was created
      if (productId) {
        await supabase.from('products').delete().eq('id', productId)
      }
    } finally {
      setSubmitting(false)
    }
  }

  return (
    <div className="min-h-screen bg-background">
      <div className="mx-auto max-w-lg px-4 py-8">
        {/* Header */}
        <div className="mb-6">
          <Link
            href="/seller/productos"
            className="flex items-center gap-1 text-sm text-muted-foreground hover:text-foreground"
          >
            <ArrowLeft className="h-4 w-4" /> Volver a productos
          </Link>
          <h1 className="mt-3 text-2xl font-bold">Agregar producto</h1>
          <p className="mt-1 text-sm text-muted-foreground">
            Completa los campos requeridos y publica tu prenda en segundos
          </p>
        </div>

        <Form {...form}>
          <form onSubmit={form.handleSubmit(onSubmit)} className="space-y-6">
            <ProductFormFields
              form={form}
              photoSlot={
                <PhotoUploader
                  photos={photos}
                  onChange={setPhotos}
                  error={photoError ?? undefined}
                />
              }
            />

            <Button
              type="submit"
              size="lg"
              disabled={submitting}
              className="w-full"
            >
              {submitting ? 'Publicando producto…' : 'Publicar producto'}
            </Button>
            <p className="text-center text-xs text-muted-foreground">
              Tu producto estará visible inmediatamente después de publicarlo
            </p>
          </form>
        </Form>
      </div>
    </div>
  )
}
